name: Playwright Tests with Docker
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run tests with Docker Compose
        run: |
          # Build the Docker image
          docker-compose build
          
          # Run the tests using the docker-compose configuration
          docker-compose up --abort-on-container-exit

      - name: Copy Allure results from container
        run: |
          # Ensure the directory exists
          mkdir -p playwright-report
          
          # Copy report files for artifact upload
          cp -r allure-report/* playwright-report/ || true

      - name: Upload test report artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Clean up
        if: always()
        run: |
          docker-compose down
          # Optionally remove volumes and images to free up space
          # docker-compose down --volumes --rmi local